env:
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    rclone_config: "ENCRYPTED[ca074debef6ade0342a30265b02c6d25cd3508e9182b3cc84dfbb6d5211c0b58c800e1e2bb4d2a89bf44fe3c3f322c09"

task:
  name: carbon
  timeout_in: 120m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G 

  chmod_script:
    - sudo chmod +x *
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  upload_script:
    - ./upload
