env:
    CIRRUS_WORKING_DIR: "/tmp/ci"
    LLVM_NAME:
    TG_TOKEN:
    TG_CHAT_ID:
    GH_USERNAME:
    GH_EMAIL:
    GH_TOKEN:
    GH_PUSH_REPO_URL:    


task:
  name: "LLVM Toolchain Compiler"
  timeout_in: 120m  
  container:
      image: xyzuan/xdocker:latest
      cpu: 8
      memory: 32G

  build_script:
      - bash llvm-tc_build.sh 
